name: Build, Test, and Deploy

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20.x]

        steps:
            - uses: actions/checkout@v4

            - name: Setup node.js
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'

            - name: Install dependencies
              run: npm install

            - name: Build project
              run: |
                  CI=false npm run build

            - name: Run tests
              run: npm test

            - name: Deploy to Remote Server
              if: success()
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_KEY }}
                  port: ${{ secrets.SSH_PORT }}
                  source: 'build/*'
                  target: '/var/www/html'

            - name: SSH Remote Commands
              if: success()
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_KEY }}
                  port: ${{ secrets.SSH_PORT }}
                  script: |
                      cd /var/www/html
                      # 여기에 원격 서버에서 실행할 명령어를 추가합니다.
                      # 예를 들어, 서비스 재시작:
                      sudo systemctl restart nginx
