name: Build and Test

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Install Dependencies and Build
              run: |
                  npm install
                  # npm test
                  npm run build

            - name: Deploy to Remote Server
              uses: appleboy/scp-action@master
              with:
                  source: 'build/*'
                  target: '/root/web'
